### ISSUE TITLE
Hard Coded GAME_SIZE

### ISSUE THREAD

**Issue by chimosky** [vaibhav-sangwan/tower-of-hanoi#1]
Why is `GAME_SIZE` hard coded?

**Comment by vaibhav-sangwan** [comment]
It's not the actual game size that is hard coded, but the size of the intermediate surface that is upscaled later on to fill up the available space. So, it's basically the base resolution of the game.

d9046576222834e8a340d1e4b589c4381c1f368a fixes this.
