### ISSUE TITLE
Flake8 issues

### ISSUE THREAD

**Issue by chimosky** [vaibhav-sangwan/tower-of-hanoi#2]
Running flake8 shows 124 errors, take a look and fix them.

**Comment by vaibhav-sangwan** [comment]
I've fixed the flake8 errors in 1a4a7620511fefb1219bc5a1ce1a94af9daf915d. It shouldn't throw any errors in the game files now. However, there are still some flake8 errors in sugargame files.

**Comment by chimosky** [comment]
Don't fix the errors in sugargame here, fix it in the sugargame repo or check to see if they've already been fixed and update the one here.
